# -*- coding: utf-8 -*-
import re
from pathlib import Path

prompts = {
1: "Photorealistic vintage photograph, 1928 Jinan, warm golden-hour tone, film grain. A stone-paved street inside the old walled city looking north to the massive grey-brick city wall and its gate tower. Brick-and-wood shops with grey tiled roofs, cloth awnings and blank signboards line both sides. Pedestrians in 1920s long gowns, a resting rickshaw puller, a loaded wheelbarrow. Fresh willow green, long soft shadows, solemn calm before catastrophe. No cars, no modern elements, no text.",
2: "Photorealistic hand-tinted photograph, late-Qing Jinan c.1880, warm desaturated tone, film grain. A broad natural spring pool, deep jade-green, far wider than an ordinary pond, many bubbling vents raising ripples across the surface. Irregular shore of rough stone and earth, old willows trailing low, locust and pine shade, mossy stone steps to the water. Grey-tiled shrine roofs half-hidden in far-bank trees. A few Qing commoners with queue hairstyles, one with a tea-kettle shoulder pole, children by the shore. No cherry blossoms, no modern elements, no text.",
3: "Photorealistic historical reconstruction, prehistoric China c.2000 BCE, misty dawn, earthy tones, film grain. A semi-cleared hillside on Mount Li, ancient Jinan, charred stumps and freshly turned dark soil from slash-and-burn farming. A tall tribal leader in rough hemp and animal hide, hair in a topknot, holds a wooden digging stick with a rope-bound stone blade, directing a dozen barefoot tribesmen planting with stone tools. Half-subterranean round thatched huts by a clear spring stream, thin smoke rising, primeval forest behind. No metal tools, no plow animals, no text.",
4: "Photorealistic historical reconstruction, Neolithic Longshan Culture China c.2500 BCE, warm daylight, ochre-brown palette, film grain. A wetland-edge settlement: semi-subterranean round houses with conical thatched roofs and wattle-and-daub walls, a low earthen wall and ring ditch behind. A figure in coarse linen and animal skin shapes a glossy jet-black eggshell-thin pottery cup; another arranges tall-stemmed black goblets and tripod vessels on a woven mat. Reeds and willows along calm water, broadleaf forest beyond. No metal objects, no written characters, no modern elements.",
5: "Photorealistic historical scene, Song-Yuan dynasty China c.1200, warm late-afternoon light, film grain. A busy dock on the Xiaoqing River, Jinan: a wooden-and-stone pier reaching into calm clear water, three flat-bottomed wooden cargo boats with furled sails moored alongside. Porters in short jackets and headscarves carry bamboo baskets and hemp sacks on shoulder poles; robed merchants negotiate, one with an abacus. Wooden shops and a riverside teahouse with grey tiled roofs and blank signboards line the willow bank, reeds at the water edge. No modern boats, no modern elements, no text.",
6: "Photorealistic vintage photograph, 1921 Jinan, kerosene lamplight, film grain. Night interior of a modest whitewashed room: four young men in dark long gowns around a square wooden table, one reading a thin pamphlet, one holding a writing brush over an inkstone, others in quiet discussion. A kerosene lamp with glass chimney casts warm gold over coarse paper, thread-bound booklets and a rough ceramic teapot; the papered lattice window shows faint night blue. Serious, intimate, idealistic mood. No electric lights, no modern furniture, no text.",
7: "Photorealistic hand-tinted photograph, late-Qing Jinan c.1900, dusk amber-to-blue sky, film grain. A vermilion wooden pleasure boat with carved window frames and half-rolled bamboo blinds drifts on the spring-fed city moat, poled by a boatwoman, a round paper lantern glowing at the bow. Left, the massive weathered Ming brick city wall with crenellations and a gate tower in silhouette; right bank, weeping willows trailing into exceptionally clear jade-green water. A shoulder-pole pedestrian on the embankment path. No motorboats, no electric lights, no text.",
8: "Photorealistic hand-tinted photograph, late-Qing Jinan c.1890, golden-hour tone, film grain. View through the dark arch of a massive stone city gate into the old town: a narrow bluestone street stretches away, a clear spring stream alongside crossed by flat stone slab bridges, weeping willows trailing over the water. Grey-tiled courtyard houses with whitewashed walls and blank wooden shop signs. Pedestrians with queues and long robes, a vendor with a shoulder pole, a man leading a donkey, a woman with a wooden water bucket. No cars, no modern elements, no text.",
9: "Photorealistic historical scene, Northern Song Jinan c.1095, soft afternoon light, film grain. A scholar's study in a courtyard house: a thirteen-year-old girl in a pale-green narrow-sleeved beizi jacket and long skirt, hair in simple double loops, sits at a low wooden desk holding a writing brush over an unrolled scroll, inkstone beside her. Behind, shelves of rolled scrolls, a guqin on a stand, a white porcelain incense burner with thin smoke. Through the papered lattice window, willows, bamboo and a distant glimpse of bubbling spring water. No modern objects, no glass windows, no text.",
10: "Photorealistic historical scene, Song dynasty Jinan c.1100, dappled late-afternoon light, film grain. A small stone spring pool barely two meters across, pale blue-grey walls, exceptionally clear water over a sandy bottom, fine air bubbles rising gently like scattered jade. A twelve-year-old girl in a pale-green narrow-sleeved jacket and flowing skirt kneels on a flat slab, rinsing a writing brush in the water, an inkstone and rolled scroll beside her. Bamboo and plantain leaves filter golden light, willow branches trail nearby, a simple grey-tiled roof corner barely visible behind. No modern elements, no glass, no text.",
11: "Photorealistic vintage photograph, 1921 Jinan, late-afternoon light, film grain. A small grey-brick courtyard of a traditional residence: two young men in dark long gowns talk quietly under a pomegranate tree, one holding a thin booklet and gesturing, the other listening with a resolute expression. A stone well with a wooden winch frame behind, low brick walls, a small wooden gate. Dappled golden light through the leaves. Earnest, secretive, purposeful mood. No modern elements, no electric lights, no text.",
12: "Photorealistic hand-tinted photograph, Qing dynasty Jinan c.1720, bright clear daylight, film grain. A rectangular spring pool of neatly fitted blue-grey stone in a governor's yamen rear garden, crystal-clear jade-green water, countless fine bubble strings rising gently from the sandy floor and breaking like rolling pearls, continuous but never boiling. A northern-Chinese pavilion with upturned eaves and red lacquered columns by the pool, Taihu rockery, willows and bamboo. A Qing official with queue hairstyle watches from the pavilion, a servant with a tea tray behind. No modern elements, no glass, no text.",
13: "Photorealistic hand-tinted photograph, late-Qing Jinan c.1890, golden-hour light, film grain. A spring-water teahouse terrace beside an irregular natural pond: low bamboo chairs and wooden tables with a purple-clay teapot on stone paving. Willows trail slender branches into the clear rippling water, water lilies near the shore, flat stone slab bridges over narrow inflowing streams. Grey-tiled whitewashed courtyard houses line the winding shore at relaxed intervals, some with stone steps to the water. A robed scholar reads a thread-bound book, a woman washes clothes on the steps. No modern elements, no asphalt, no text.",
14: "Photorealistic vintage photograph, 1920s Jinan commercial port, raking afternoon light, film grain. Wei'er Road financial street: a continuous wall of two- and three-story European classical banks, a grand German Neoclassical bank with granite steps, four-column Ionic portico and carved triangular pediment as focal point, flanked by British red-brick buildings and a few Chinese-Western hybrids with tiled roofs. Cast-iron gates, stone lions at the steps. Clerks in Western suits, compradors in long gowns, waiting rickshaws, one early black boxy automobile. Cobblestones, cast-iron lamps, plane trees. No modern cars, no neon signs, no text.",
15: "Photorealistic vintage photograph, 1920s Jinan commercial port, warm late-afternoon light, film grain. Jing'er Road commercial axis: a continuous street wall of one- to three-story Chinese-Western hybrids, Western arched porches, pediments and cast-iron balconies mixed with grey-brick Chinese shops with wooden lattice windows and pitched tile roofs. Cloth banners and blank signboards above open shopfronts. Cobblestone street, pedestrians in long gowns, qipao and a few Western suits, rickshaws, a distant early automobile. Cast-iron street lamps, plane trees, gentle haze. No modern cars, no asphalt, no text.",
16: "Photorealistic vintage photograph, 1904 Jinan, crisp morning side-light, film grain. The Jiaoji Railway station: a symmetrical two-story German Neoclassical building in red brick and stone, central columned porch with wide granite steps, tall arched windows with stone surrounds, red-tiled hipped roof, a lower eastern annex with dormers. At the low open platform, a 1900s German steam locomotive breathing soft white steam with riveted wooden carriages. German engineers in suits and caps, Chinese laborers in short jackets, long-gowned travelers. Crushed-stone square, sparse pines. No tall clock tower, no overhead wires or modern trains, no text.",
17: "Photorealistic vintage photograph, c.1905 Jinan, slanting morning light, film grain. A narrow commercial lane paved with worn dew-glistening bluestone slabs, tight rows of grey-tiled shop-houses, open shopfronts with wooden counters, blank vertical signboards and fluttering cloth banners. Left, a vendor fries golden spiral pastries on a sizzling iron griddle beside stacked bamboo steamers; customers in long robes eat at low tables. Right, a half-open courtyard gate reveals a small square spring pool with pink hibiscus behind a brick screen wall. The red wall and glazed roof of the Confucian temple close the vista. No cars, no modern elements, no text.",
18: "Photorealistic hand-tinted photograph, late-Qing Jinan c.1890, golden-hour light, film grain. Across a clear spring-fed moat, the southeastern corner of the Ming-era city wall: weathered blue-grey brick rising ten meters, intact crenellated parapets, a small angled bastion, moss patches. Willows line both banks, branches touching the calm water. To the right, the ancient Black Tiger Spring: a stone pool with ONE single rustic stone beast-head spout gushing a powerful clear stream, only one spout existed before 1931. A woman washes clothes on the bank, late-Qing figures stroll the wall top, hazy Mount Qianfo beyond. No pavilion on the wall, no modern buildings, no text.",
19: "Photorealistic historical scene, Southern Song China c.1180, oil-lamp warmth against cold moonlight, film grain. Night in a scholar-warrior's timber study, exposed beams, papered lattice windows. A robust man in his late thirties, reddish cheeks and short beard, in a dark indigo robe and slightly askew square cap, adjusts the lamp wick with his left hand while his right grips a sheathed sword. On the desk: an ink-written scroll, inkstone, celadon wine pot and cup, scattered drafts. A second sword and a bow on a wall rack, a guqin by the scroll-filled shelf, moonlit bamboo shadows outside. No glass windows, no blue-and-white porcelain, no text.",
20: "Photorealistic hand-tinted photograph, Qing dynasty Jinan c.1800, soft morning light and lake mist, film grain. A modest memorial temple by Daming Lake, central-axis view: a single-eaved hard-gable gatehouse with grey tiles and a blank horizontal plaque, stone steps, wooden double doors, two medium stone lions. Inside, a stone-paved courtyard with tall pines and bamboo; at the far end a three-bay main hall with grey hip-and-gable roof, an offering table with bronze incense burner within. A stele on a tortoise base under the pines. Through the trees, lotus and willows on the lake, faint silhouette of Thousand Buddha Mountain. No modern buildings, no glass, no text.",
}

path = Path(r"W:\Agente_Inteligente\quancheng-agents\prompts-v7-批量生图对照表.md")
src = path.read_text(encoding="utf-8")
blocks = list(re.finditer(r"```\n(Photorealistic.*?)\n```", src, re.S))
assert len(blocks) == 20, len(blocks)
out, last = [], 0
for i, m in enumerate(blocks, 1):
    p = prompts[i]
    print(("OK " if len(p) <= 512 else "OVER"), i, len(p))
    out.append(src[last:m.start()])
    out.append("```\n" + p + "\n```")
    last = m.end()
out.append(src[last:])
path.write_text("".join(out), encoding="utf-8")
print("written")
